apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: serveup-app
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/OzAmoyal/ArgoCD-learning
    targetRevision: HEAD
    path: dev

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: serveup-namespace
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true